//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DoseConverter {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DoseConverterConfig {
        
        private DoseConverterConfigVersion versionField;
        
        private DoseConverterConfigDefaults defaultsField;
        
        private DoseConverterConfigStructure[] structuresField;
        
        private DoseConverterConfigRegistrationParameters registrationParametersField;
        
        private DoseConverterConfigSitePreset[] sitePresetsField;
        
        /// <remarks/>
        public DoseConverterConfigVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DoseConverterConfigDefaults Defaults {
            get {
                return this.defaultsField;
            }
            set {
                this.defaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Structure", IsNullable=false)]
        public DoseConverterConfigStructure[] Structures {
            get {
                return this.structuresField;
            }
            set {
                this.structuresField = value;
            }
        }
        
        /// <remarks/>
        public DoseConverterConfigRegistrationParameters RegistrationParameters {
            get {
                return this.registrationParametersField;
            }
            set {
                this.registrationParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SitePreset", IsNullable=false)]
        public DoseConverterConfigSitePreset[] SitePresets {
            get {
                return this.sitePresetsField;
            }
            set {
                this.sitePresetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigVersion {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigDefaults {
        
        private double alphaBetaRatioField;
        
        private string tempEdgeStructureNameField;
        
        private string tempStructureSetNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double AlphaBetaRatio {
            get {
                return this.alphaBetaRatioField;
            }
            set {
                this.alphaBetaRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TempEdgeStructureName {
            get {
                return this.tempEdgeStructureNameField;
            }
            set {
                this.tempEdgeStructureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TempStructureSetName {
            get {
                return this.tempStructureSetNameField;
            }
            set {
                this.tempStructureSetNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigStructure {
        
        private DoseConverterConfigStructureAlias[] aliasesField;
        
        private string structureLabelField;
        
        private double maxEQD2Field;
        
        private bool maxEQD2FieldSpecified;
        
        private double alphaBetaRatioField;
        
        private bool forceEdgeConversionField;
        
        public DoseConverterConfigStructure() {
            this.forceEdgeConversionField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Alias", IsNullable=false)]
        public DoseConverterConfigStructureAlias[] Aliases {
            get {
                return this.aliasesField;
            }
            set {
                this.aliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructureLabel {
            get {
                return this.structureLabelField;
            }
            set {
                this.structureLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MaxEQD2 {
            get {
                return this.maxEQD2Field;
            }
            set {
                this.maxEQD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxEQD2Specified {
            get {
                return this.maxEQD2FieldSpecified;
            }
            set {
                this.maxEQD2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double AlphaBetaRatio {
            get {
                return this.alphaBetaRatioField;
            }
            set {
                this.alphaBetaRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ForceEdgeConversion {
            get {
                return this.forceEdgeConversionField;
            }
            set {
                this.forceEdgeConversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigStructureAlias {
        
        private string structureIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructureId {
            get {
                return this.structureIdField;
            }
            set {
                this.structureIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigRegistrationParameters {
        
        private RegistrationAlgorithmType registrationAlgorithmField;
        
        private string bSplineGridNodesField;

        private double bSplineControlPointSpacingField;

        private string bSplineOrderField;
        
        private double metricSamplingPercentageField;
        
        private double gradientConvergenceToleranceField;
        
        private string maxIterationsField;
        
        private string maxCorrectionsField;
        
        private string maxFunctionEvaluationsField;
        
        private double costFunctionConvergenceFactorField;
        
        private string shrinkFactorsPerLevelField;
        
        private string smoothingSigmasPerLevelField;
        
        private string maxIterationsPerLevelField;
        
        private double maskMarginMmField;
        
        private string demonsStandardDeviationsField;
        
        private double demonsMaxStepLengthField;
        
        private string dicomExportDirectoryField;
        
        public DoseConverterConfigRegistrationParameters() {
            this.registrationAlgorithmField = RegistrationAlgorithmType.Demons;
            this.bSplineGridNodesField = "12 12 8";
            this.bSplineControlPointSpacingField = 20D;
            this.bSplineOrderField = "3";
            this.metricSamplingPercentageField = 1D;
            this.gradientConvergenceToleranceField = 1E-05D;
            this.maxIterationsField = "100";
            this.maxCorrectionsField = "5";
            this.maxFunctionEvaluationsField = "1000";
            this.costFunctionConvergenceFactorField = 0D;
            this.shrinkFactorsPerLevelField = "4 2 1";
            this.smoothingSigmasPerLevelField = "2.0 1.0 0.0";
            this.maxIterationsPerLevelField = "50 30 20";
            this.maskMarginMmField = 20D;
            this.demonsStandardDeviationsField = "1.0";
            this.demonsMaxStepLengthField = 2D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RegistrationAlgorithmType.Demons)]
        public RegistrationAlgorithmType RegistrationAlgorithm {
            get {
                return this.registrationAlgorithmField;
            }
            set {
                this.registrationAlgorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("12 12 8")]
        public string BSplineGridNodes {
            get {
                return this.bSplineGridNodesField;
            }
            set {
                this.bSplineGridNodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(20D)]
        public double BSplineControlPointSpacing {
            get {
                return this.bSplineControlPointSpacingField;
            }
            set {
                this.bSplineControlPointSpacingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("3")]
        public string BSplineOrder {
            get {
                return this.bSplineOrderField;
            }
            set {
                this.bSplineOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double MetricSamplingPercentage {
            get {
                return this.metricSamplingPercentageField;
            }
            set {
                this.metricSamplingPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1E-05D)]
        public double GradientConvergenceTolerance {
            get {
                return this.gradientConvergenceToleranceField;
            }
            set {
                this.gradientConvergenceToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("100")]
        public string MaxIterations {
            get {
                return this.maxIterationsField;
            }
            set {
                this.maxIterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("5")]
        public string MaxCorrections {
            get {
                return this.maxCorrectionsField;
            }
            set {
                this.maxCorrectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1000")]
        public string MaxFunctionEvaluations {
            get {
                return this.maxFunctionEvaluationsField;
            }
            set {
                this.maxFunctionEvaluationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double CostFunctionConvergenceFactor {
            get {
                return this.costFunctionConvergenceFactorField;
            }
            set {
                this.costFunctionConvergenceFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("4 2 1")]
        public string ShrinkFactorsPerLevel {
            get {
                return this.shrinkFactorsPerLevelField;
            }
            set {
                this.shrinkFactorsPerLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("2.0 1.0 0.0")]
        public string SmoothingSigmasPerLevel {
            get {
                return this.smoothingSigmasPerLevelField;
            }
            set {
                this.smoothingSigmasPerLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("50 30 20")]
        public string MaxIterationsPerLevel {
            get {
                return this.maxIterationsPerLevelField;
            }
            set {
                this.maxIterationsPerLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(20D)]
        public double MaskMarginMm {
            get {
                return this.maskMarginMmField;
            }
            set {
                this.maskMarginMmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("1.0")]
        public string DemonsStandardDeviations {
            get {
                return this.demonsStandardDeviationsField;
            }
            set {
                this.demonsStandardDeviationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(2D)]
        public double DemonsMaxStepLength {
            get {
                return this.demonsMaxStepLengthField;
            }
            set {
                this.demonsMaxStepLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DicomExportDirectory {
            get {
                return this.dicomExportDirectoryField;
            }
            set {
                this.dicomExportDirectoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum RegistrationAlgorithmType {
        
        /// <remarks/>
        Demons,
        
        /// <remarks/>
        BSpline,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigSitePreset {
        
        private string nameField;
        
        private double stdDevField;
        
        private string iterationsField;

        private double maxStepLengthField;

        private double bSplineSpacingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double StdDev {
            get {
                return this.stdDevField;
            }
            set {
                this.stdDevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Iterations {
            get {
                return this.iterationsField;
            }
            set {
                this.iterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MaxStepLength {
            get {
                return this.maxStepLengthField;
            }
            set {
                this.maxStepLengthField = value;
            }
        }

        /// <remarks/>
        /// <summary>B-spline control-point spacing (mm) for this site. 0 = use the global default.</summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double BSplineSpacing {
            get {
                return this.bSplineSpacingField;
            }
            set {
                this.bSplineSpacingField = value;
            }
        }
    }
}
