//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DoseConverter {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DoseConverterConfig {
        
        private DoseConverterConfigVersion versionField;
        
        private DoseConverterConfigDefaults defaultsField;
        
        private DoseConverterConfigStructure[] structuresField;
        
        private DoseConverterConfigRegistrationParameters registrationParametersField;
        
        /// <remarks/>
        public DoseConverterConfigVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DoseConverterConfigDefaults Defaults {
            get {
                return this.defaultsField;
            }
            set {
                this.defaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Structure", IsNullable=false)]
        public DoseConverterConfigStructure[] Structures {
            get {
                return this.structuresField;
            }
            set {
                this.structuresField = value;
            }
        }
        
        /// <remarks/>
        public DoseConverterConfigRegistrationParameters RegistrationParameters {
            get {
                return this.registrationParametersField;
            }
            set {
                this.registrationParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigVersion {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigDefaults {
        
        private double alphaBetaRatioField;
        
        private string tempEdgeStructureNameField;
        
        private string tempStructureSetNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double AlphaBetaRatio {
            get {
                return this.alphaBetaRatioField;
            }
            set {
                this.alphaBetaRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TempEdgeStructureName {
            get {
                return this.tempEdgeStructureNameField;
            }
            set {
                this.tempEdgeStructureNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TempStructureSetName {
            get {
                return this.tempStructureSetNameField;
            }
            set {
                this.tempStructureSetNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigStructure {
        
        private DoseConverterConfigStructureAlias[] aliasesField;
        
        private string structureLabelField;
        
        private double maxEQD2Field;
        
        private bool maxEQD2FieldSpecified;
        
        private double alphaBetaRatioField;
        
        private bool forceEdgeConversionField;
        
        public DoseConverterConfigStructure() {
            this.forceEdgeConversionField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Alias", IsNullable=false)]
        public DoseConverterConfigStructureAlias[] Aliases {
            get {
                return this.aliasesField;
            }
            set {
                this.aliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructureLabel {
            get {
                return this.structureLabelField;
            }
            set {
                this.structureLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MaxEQD2 {
            get {
                return this.maxEQD2Field;
            }
            set {
                this.maxEQD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxEQD2Specified {
            get {
                return this.maxEQD2FieldSpecified;
            }
            set {
                this.maxEQD2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double AlphaBetaRatio {
            get {
                return this.alphaBetaRatioField;
            }
            set {
                this.alphaBetaRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ForceEdgeConversion {
            get {
                return this.forceEdgeConversionField;
            }
            set {
                this.forceEdgeConversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigStructureAlias {
        
        private string structureIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StructureId {
            get {
                return this.structureIdField;
            }
            set {
                this.structureIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DoseConverterConfigRegistrationParameters {
        
        private string bSplineGridNodesField;
        
        private string bSplineOrderField;
        
        private double metricSamplingPercentageField;
        
        private double gradientConvergenceToleranceField;
        
        private string maxIterationsField;
        
        private string maxCorrectionsField;
        
        private string maxFunctionEvaluationsField;
        
        private double costFunctionConvergenceFactorField;
        
        private string shrinkFactorsPerLevelField;
        
        private string smoothingSigmasPerLevelField;
        
        public DoseConverterConfigRegistrationParameters() {
            this.bSplineGridNodesField = "5 5 5";
            this.bSplineOrderField = "3";
            this.metricSamplingPercentageField = 0.1D;
            this.gradientConvergenceToleranceField = 1E-05D;
            this.maxIterationsField = "100";
            this.maxCorrectionsField = "5";
            this.maxFunctionEvaluationsField = "1000";
            this.costFunctionConvergenceFactorField = 10000000D;
            this.shrinkFactorsPerLevelField = "4 2 1";
            this.smoothingSigmasPerLevelField = "2.0 1.0 0.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("5 5 5")]
        public string BSplineGridNodes {
            get {
                return this.bSplineGridNodesField;
            }
            set {
                this.bSplineGridNodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("3")]
        public string BSplineOrder {
            get {
                return this.bSplineOrderField;
            }
            set {
                this.bSplineOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0.1D)]
        public double MetricSamplingPercentage {
            get {
                return this.metricSamplingPercentageField;
            }
            set {
                this.metricSamplingPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1E-05D)]
        public double GradientConvergenceTolerance {
            get {
                return this.gradientConvergenceToleranceField;
            }
            set {
                this.gradientConvergenceToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("100")]
        public string MaxIterations {
            get {
                return this.maxIterationsField;
            }
            set {
                this.maxIterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("5")]
        public string MaxCorrections {
            get {
                return this.maxCorrectionsField;
            }
            set {
                this.maxCorrectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1000")]
        public string MaxFunctionEvaluations {
            get {
                return this.maxFunctionEvaluationsField;
            }
            set {
                this.maxFunctionEvaluationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(10000000D)]
        public double CostFunctionConvergenceFactor {
            get {
                return this.costFunctionConvergenceFactorField;
            }
            set {
                this.costFunctionConvergenceFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("4 2 1")]
        public string ShrinkFactorsPerLevel {
            get {
                return this.shrinkFactorsPerLevelField;
            }
            set {
                this.shrinkFactorsPerLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("2.0 1.0 0.0")]
        public string SmoothingSigmasPerLevel {
            get {
                return this.smoothingSigmasPerLevelField;
            }
            set {
                this.smoothingSigmasPerLevelField = value;
            }
        }
    }
}
